### PR TITLE
max his solution to warmup-002.rb + a README

### PR DESCRIPTION
**Pull request by Netznarkose**
hi gustavo, this is just an exercise for me to practice the pull request, you already know the script, but can you tell me if i did the "pulling" correct?
and by the way, do you know how the git branch editor is called that this guy in this video uses(his right terminal), it looks pretty cool...
+greetings max
+https://www.youtube.com/watch?v=CUpk6F2eNs0
ps: forget about the readme in the folder, the infos are here...

### CODE REVIEW

**Comment by gustavoguimaraes** [comment]
Congratulations, this is your first pull request :+1:

You did exactly right. I am not going to merge because it will overwrite the warm-up files I created, but the process you got it right. 

As for what you saw on the video, my hunch is that the person is using an alternative terminal such as Iterm(http://iterm2.com/) and he configured git log adding a alias such as this guy did: http://uberblo.gs/2010/12/git-lol-the-other-git-log

If you follow the instructions in this blog post once you type "git lol" it should show something similar to what you saw.

**Comment by gustavoguimaraes** [comment]
By the way, did you figure out the issue of adding your ssh key to Bitbucket? I would like to learn how you solved it.

**Comment by Netznarkose** [comment]
hi gustiavo, thanx for your fast reply. a friend of mine helped me with the .ssh problem and i think the matter where the file-permissions, in the end it worked out, but later when i tried to add another key for my github-account  i ran into new difficulties, so this is still an issue, but certainly not the most important one...
and about the terminal -emulator or -multiplexer or however they are called: i heard that tmux is a good choice for a vim-ruby &rails workflow do you have any experience with that one? right now i stick to the good old mac-terminal  - just to avoid a "brain stack owerflow" - but at least i configured a git status prompt yesterday instructed by: https://github.com/jimeh/git-aware-prompt

**Comment by gustavoguimaraes** [comment]
I hear tmux is great, but I have not had the chance to use it yet. Maybe we can learn together. I actually have to use more vim, I would love to learn it from you.

**Comment by Netznarkose** [comment]
yesterday i went to this event: http://vimberlin.de/january-2015-meetup/ so the motivation to get into vim exists... if you would like to meet one day and exchange experience, lovely, let's do it! .... by the way I found out that the git log --oneline --graph --branches command draws the nice graph in git.

**Comment by Netznarkose** [comment]
hi gustavo, just wanted to ask you if you are preparing another exercise for tomorrow?
I made one exercise up that is more or less a logical continuance of warmup 001 & 002.
we would have prompting and array-handling in one script and a if-statement inside a loop as a new element. what do you think?
ps: this could also be a voluntary homework if you're or somebody else is already prepared...

array = []

begin
puts "entry = 1, show list = 2, stop = 0"
var_menue = gets.chomp.to_i

  if var_menue == 1
    puts "vorname"
    var_vorname = gets.chomp  
    puts "nachname"
    var_nachname = gets.chomp
    puts "github name"
    var_github = gets.chomp
    array.push "#{var_vorname} #{var_nachname}  #{var_github}"
  else
    puts array
  end 
end until var_menue == 0

**Comment by gustavoguimaraes** [comment]
Hey Max,

Sorry just saw this today. Yeah send me a pull request with the warmup
exercise tonight. Make sure you create a file named "warmup-003.rb"

Looking forward to looking into it

Gustavo

**Comment by gustavoguimaraes** [comment]
Also, what is your email?

**Pull request closed without merging**
